{{- if and .Values.fleetdm.enabled .Values.fleetdm.prepareDB.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fleetdm.fullname" . }}-prepare-db
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
    app.kubernetes.io/component: prepare-db
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.fleetdm.prepareDB.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "fleetdm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prepare-db
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            until nc -z {{ include "fleetdm.mysql.address" . | replace ":3306" "" }} 3306; do
              echo "Waiting for MySQL to be ready..."
              sleep 2
            done
            echo "MySQL is ready!"
      containers:
      - name: prepare-db
        image: "{{ .Values.fleetdm.prepareDB.image.repository }}:{{ .Values.fleetdm.prepareDB.image.tag }}"
        imagePullPolicy: {{ .Values.fleetdm.image.pullPolicy }}
        command:
          - fleet
          - prepare
          - db
          - --config
          - /etc/fleetdm/fleet.yml
        env:
        - name: FLEET_MYSQL_ADDRESS
          value: {{ include "fleetdm.mysql.address" . }}
        - name: FLEET_MYSQL_DATABASE
          value: {{ .Values.fleetdm.config.mysql.database | default "fleet" }}
        - name: FLEET_MYSQL_USERNAME
          value: {{ .Values.fleetdm.config.mysql.username | default "fleet" }}
        - name: FLEET_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fleetdm.fullname" . }}-secrets
              key: mysql-password
        volumeMounts:
        - name: config
          mountPath: /etc/fleetdm/fleet.yml
          subPath: fleet.yml
        - name: secrets
          mountPath: /etc/fleetdm/secrets
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "fleetdm.fullname" . }}-config
      - name: secrets
        secret:
          secretName: {{ include "fleetdm.fullname" . }}-secrets
{{- end }}

