{{- if .Values.fleetdm.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetdm.fullname" . }}-secrets
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
type: Opaque
{{- $mysqlSecretName := printf "%s-mysql-secret" (include "fleetdm.fullname" .) }}
{{- $redisSecretName := printf "%s-redis-secret" (include "fleetdm.fullname" .) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" (include "fleetdm.fullname" .))) }}
{{- $existingMysqlSecret := (lookup "v1" "Secret" .Release.Namespace $mysqlSecretName) }}
{{- $existingRedisSecret := (lookup "v1" "Secret" .Release.Namespace $redisSecretName) }}
{{- if $existingSecret }}
data:
  mysql-password: {{ index $existingSecret.data "mysql-password" }}
  redis-password: {{ index $existingSecret.data "redis-password" }}
  jwt-key: {{ index $existingSecret.data "jwt-key" }}
  enroll-secret: {{ index $existingSecret.data "enroll-secret" }}
{{- else }}
{{- $mysqlPassword := "" }}
{{- $redisPassword := "" }}
{{- if .Values.fleetdm.config.mysql.password }}
  {{- $mysqlPassword = .Values.fleetdm.config.mysql.password }}
{{- else if .Values.mysql.auth.password }}
  {{- $mysqlPassword = .Values.mysql.auth.password }}
{{- else if and .Values.mysql.enabled $existingMysqlSecret }}
  {{- $mysqlPassword = (index $existingMysqlSecret.data "password" | b64dec) }}
{{- else }}
  {{- $mysqlPassword = (randAlphaNum 32) }}
{{- end }}
{{- if .Values.fleetdm.config.redis.password }}
  {{- $redisPassword = .Values.fleetdm.config.redis.password }}
{{- else if .Values.redis.auth.password }}
  {{- $redisPassword = .Values.redis.auth.password }}
{{- else if and .Values.redis.enabled $existingRedisSecret }}
  {{- $redisPassword = (index $existingRedisSecret.data "password" | b64dec) }}
{{- else }}
  {{- $redisPassword = (randAlphaNum 32) }}
{{- end }}
data:
  mysql-password: {{ $mysqlPassword | b64enc }}
  redis-password: {{ $redisPassword | b64enc }}
  {{- if .Values.fleetdm.config.auth.jwt_key }}
  jwt-key: {{ .Values.fleetdm.config.auth.jwt_key | b64enc }}
  {{- else }}
  jwt-key: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
  {{- if .Values.fleetdm.config.osquery.enroll_secret }}
  enroll-secret: {{ .Values.fleetdm.config.osquery.enroll_secret | b64enc }}
  {{- else }}
  enroll-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

