{{- if .Values.fleetdm.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetdm.fullname" . }}-secrets
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
type: Opaque
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-secrets" (include "fleetdm.fullname" .))) }}
{{- if $existingSecret }}
data:
  mysql-password: {{ index $existingSecret.data "mysql-password" }}
  redis-password: {{ index $existingSecret.data "redis-password" }}
  jwt-key: {{ index $existingSecret.data "jwt-key" }}
  enroll-secret: {{ index $existingSecret.data "enroll-secret" }}
{{- else }}
data:
  {{- if .Values.fleetdm.config.mysql.password }}
  mysql-password: {{ .Values.fleetdm.config.mysql.password | b64enc }}
  {{- else if .Values.mysql.enabled }}
  mysql-password: {{ .Values.mysql.auth.password | default (randAlphaNum 32) | b64enc }}
  {{- else }}
  mysql-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if .Values.fleetdm.config.redis.password }}
  redis-password: {{ .Values.fleetdm.config.redis.password | b64enc }}
  {{- else if .Values.redis.enabled }}
  redis-password: {{ .Values.redis.auth.password | default (randAlphaNum 32) | b64enc }}
  {{- else }}
  redis-password: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
  {{- if .Values.fleetdm.config.auth.jwt_key }}
  jwt-key: {{ .Values.fleetdm.config.auth.jwt_key | b64enc }}
  {{- else }}
  jwt-key: {{ randAlphaNum 64 | b64enc }}
  {{- end }}
  {{- if .Values.fleetdm.config.osquery.enroll_secret }}
  enroll-secret: {{ .Values.fleetdm.config.osquery.enroll_secret | b64enc }}
  {{- else }}
  enroll-secret: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

